import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, rm, mkdir, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";

// Run after npm run build. A separately installed Playwright can be provided here.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : "playwright");
const directory = await mkdtemp(path.join(tmpdir(), "sns-map-browser-test-"));
const base = "http://localhost:3218";
const key = "browser-map-test-key";
const server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "start", "-p", "3218"], { cwd: process.cwd(), env: { ...process.env, ADMIN_MAP_TOKEN: key, MAP_IMAGES_DATA_DIR: directory, MAP_IMAGES_UPLOAD_DIR: path.join(directory, "uploads") }, stdio: "ignore", windowsHide: true });
let browser;
let page;
try {
  for (let attempt = 0; attempt < 100; attempt++) {
    try { if ((await fetch(`${base}/api/map-images`)).ok) break; } catch {}
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  browser = await chromium.launch({ headless: true, ...(process.env.TEST_BROWSER_PATH ? { executablePath: process.env.TEST_BROWSER_PATH } : {}) });
  page = await browser.newPage({ httpCredentials: { username: "admin", password: key }, viewport: { width: 1440, height: 1100 } });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`${base}/admin`);
  await page.locator(".map-marker-overlay").first().waitFor({ timeout: 30000 });
  assert.equal(await page.locator(".map-marker-overlay").count(), 4);
  const canvas = page.getByRole("region", { name: "Map", exact: true });
  const bounds = await canvas.boundingBox();
  assert.ok(bounds);
  await page.mouse.click(bounds.x + bounds.width * 0.65, bounds.y + bounds.height * 0.62, { button: "right" });
  await page.getByRole("menuitem", { name: "Add marker" }).click();
  await page.getByRole("textbox", { name: "Marker name" }).fill("browser-marker");
  const image = page.locator('.map-marker-overlay').filter({ has: page.getByRole("button", { name: "browser-marker", exact: true }) });
  await image.waitFor();
  assert.equal(await image.locator("svg.lucide-map-pin").count(), 1);
  await page.getByLabel("Destination photo", { exact: true }).setInputFiles({ name: "marker.png", mimeType: "image/png", buffer: await readFile("public/ihub.png") });
  await page.getByRole("status").filter({ hasText: "Photo added." }).waitFor();
  assert.equal(await image.locator("img").count(), 0);
  assert.equal(await image.locator("svg.lucide-map-pin").count(), 1);
  assert.equal(await page.locator(".map-marker-overlay").count(), 5);
  assert.equal((await (await fetch(`${base}/api/map-images`)).json()).images.length, 4, "Unpublished marker must remain private");
  const start = await image.boundingBox();
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2);
  await page.mouse.down();
  await page.mouse.move(start.x + start.width / 2 + 35, start.y + start.height / 2 + 25, { steps: 10 });
  await page.mouse.up();
  const moved = await image.boundingBox();
  assert.ok(Math.abs(moved.x - start.x - 35) < 3, "Image should move with pointer");
  await image.getByRole("button").focus();
  await page.keyboard.press("Enter");
  assert.equal(await page.getByRole("textbox", { name: "Marker name" }).inputValue(), "browser-marker");
  await page.getByText("Admin publish key", { exact: true }).click();
  await page.getByRole("textbox", { name: "Admin publish key", exact: true }).fill(key);
  await page.getByRole("button", { name: "Save / Publish", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Published." }).waitFor();
  const published = await (await fetch(`${base}/api/map-images`)).json();
  assert.equal(published.images.length, 5);
  assert.match(published.images.at(-1).src, /^\/uploads\/map-images\/.+\.png$/);
  assert.equal(published.images.at(-1).locationId, published.images.at(-1).id);
  await mkdir("test-results", { recursive: true });
  await page.screenshot({ path: "test-results/map-image-editor.png", fullPage: true });
  const publicPage = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await publicPage.goto(base);
  await publicPage.getByRole("button", { name: "Open settings", exact: true }).click();
  const settings = publicPage.getByRole("dialog", { name: "Settings", exact: true });
  await settings.waitFor();
  await settings.getByRole("textbox", { name: "Your name" }).fill("Campus visitor");
  await settings.getByRole("radio", { name: "Red", exact: true }).locator("..").click();
  await settings.getByRole("radio", { name: "Satellite", exact: false }).locator("..").click();
  await mkdir("test-results", { recursive: true });
  await settings.locator(".overflow-y-auto").evaluate((element) => { element.scrollTop = 0; });
  await publicPage.screenshot({ path: "test-results/settings-desktop.png" });
  for (const viewport of [{ width: 390, height: 844 }, { width: 320, height: 568 }, { width: 844, height: 390 }]) {
    await publicPage.setViewportSize(viewport);
    const rect = await settings.boundingBox();
    assert.ok(rect.x >= 0 && rect.y >= 0 && rect.x + rect.width <= viewport.width + 1 && rect.y + rect.height <= viewport.height + 1, "Settings fits the viewport");
    assert.ok(await settings.evaluate((element) => element.scrollWidth <= element.clientWidth), "Settings has no horizontal overflow");
    const saveRect = await settings.getByRole("button", { name: "Save settings" }).boundingBox();
    assert.ok(saveRect.y + saveRect.height <= viewport.height, "Save stays visible");
    await publicPage.screenshot({ path: `test-results/settings-${viewport.width}.png` });
  }
  await settings.getByRole("button", { name: "Save settings" }).click();
  assert.equal(await settings.count(), 0);
  await publicPage.getByRole("button", { name: "Open settings", exact: true }).click();
  assert.equal(await settings.getByRole("textbox", { name: "Your name" }).inputValue(), "Campus visitor");
  assert.equal(await settings.getByRole("radio", { name: "Red", exact: true }).isChecked(), true);
  await settings.getByRole("textbox", { name: "Your name" }).fill("Discard this edit");
  await publicPage.keyboard.press("Escape");
  await publicPage.getByRole("button", { name: "Open settings", exact: true }).click();
  assert.equal(await settings.getByRole("textbox", { name: "Your name" }).inputValue(), "Campus visitor");
  await settings.getByRole("radio", { name: "Standard", exact: false }).locator("..").click();
  await settings.getByRole("button", { name: "Save settings" }).click();
  await publicPage.setViewportSize({ width: 1440, height: 1000 });
  const publicMarker = publicPage.locator('.map-marker-overlay button[title="browser-marker"]');
  await publicMarker.waitFor({ timeout: 30000 });
  assert.equal(await publicMarker.locator("img").count(), 0);
  assert.equal(await publicMarker.locator("svg.lucide-map-pin").count(), 1);
  await publicMarker.click();
  await publicPage.getByRole("heading", { name: "browser-marker", exact: true }).waitFor();
  const detailImage = publicPage.locator('img[alt="browser-marker"]');
  await detailImage.waitFor();
  await detailImage.evaluate((element) => element.decode());
  assert.ok((await detailImage.getAttribute("src")).includes(encodeURIComponent(published.images.at(-1).src)) || (await detailImage.getAttribute("src")) === published.images.at(-1).src);
  await publicPage.setViewportSize({ width: 390, height: 844 });
  const sheet = publicPage.getByRole("complementary", { name: "browser-marker details" });
  const grip = sheet.locator(".sheet-grip");
  assert.ok(Math.abs((await sheet.boundingBox()).height - 844 * .82) < 2, "Marker details leave the map visible on mobile");
  await grip.click();
  const initialSheet = await sheet.boundingBox();
  const gripBox = await grip.boundingBox();
  await publicPage.mouse.move(gripBox.x + gripBox.width / 2, gripBox.y + gripBox.height / 2);
  await publicPage.mouse.down();
  await publicPage.mouse.move(gripBox.x + gripBox.width / 2, gripBox.y - 300, { steps: 15 });
  assert.notEqual(await sheet.evaluate((element) => element.style.transform), "", "Dragging uses a transform");
  await publicPage.mouse.up();
  assert.ok((await sheet.boundingBox()).height > initialSheet.height + 200, "Panel expands after dragging");
  assert.equal(await sheet.evaluate((element) => element.style.transform), "", "Drag transform clears on release");
  await grip.click();
  assert.ok((await sheet.boundingBox()).height < 400, "Tap collapses panel");
  await grip.focus();
  await publicPage.keyboard.press("Enter");
  assert.ok((await sheet.boundingBox()).height > 600, "Keyboard expands panel");
  await publicPage.setViewportSize({ width: 320, height: 568 });
  assert.ok((await sheet.boundingBox()).height <= 568 * .82 + 1);
  assert.ok(await sheet.evaluate((element) => element.scrollWidth <= element.clientWidth), "No horizontal overflow on small screens");
  await publicPage.setViewportSize({ width: 844, height: 390 });
  assert.ok((await sheet.boundingBox()).height <= 390 * .82 + 1, "Panel adapts to landscape");
  await publicPage.setViewportSize({ width: 1440, height: 1000 });
  assert.equal(await grip.isVisible(), false, "Desktop retains the sidebar");
  await publicPage.context().grantPermissions(["geolocation"]);
  await publicPage.context().setGeolocation({ latitude: 11.099, longitude: 77.026, accuracy: 5 });
  const destination = published.images.at(-1);
  // A deterministic route fixture checks UI independently of the external router.
  await publicPage.route("**/route/v1/**", (route) => route.fulfill({ json: { code: "Ok", routes: [{ distance: 350, duration: 250, geometry: { coordinates: [[77.026, 11.099], [destination.lng, destination.lat]] } }] } }));
  await publicPage.setViewportSize({ width: 390, height: 844 });
  await publicPage.getByRole("button", { name: "Directions", exact: true }).click();
  await publicPage.getByRole("button", { name: "Start", exact: true }).waitFor();
  await publicPage.screenshot({ path: "test-results/route-mobile.png" });
  await publicPage.setViewportSize({ width: 844, height: 390 });
  await publicPage.getByRole("button", { name: "Start", exact: true }).scrollIntoViewIfNeeded();
  await publicPage.screenshot({ path: "test-results/route-landscape.png" });
  await publicPage.setViewportSize({ width: 390, height: 844 });
  await publicPage.getByRole("button", { name: "Start", exact: true }).click();
  await publicPage.getByRole("button", { name: "Exit", exact: true }).waitFor();
  await publicPage.screenshot({ path: "test-results/navigation-mobile.png" });
  await publicPage.getByRole("button", { name: "Exit", exact: true }).click();
  await publicPage.getByRole("button", { name: "Saved places" }).click();
  await publicPage.getByText("Save a place to find it here later.").waitFor();
  await publicPage.getByRole("button", { name: "Explore", exact: true }).click();
  await publicPage.getByRole("textbox", { name: "Search campus" }).fill("browser-marker");
  await publicPage.getByRole("button", { name: /browser-marker/ }).last().click();
  await publicPage.getByRole("heading", { name: "browser-marker", exact: true }).waitFor();
  await publicPage.screenshot({ path: "test-results/details-mobile.png" });
  await page.reload();
  await page.locator('.map-marker-overlay button[title="browser-marker"]').waitFor({ timeout: 30000 });
  await page.locator('.map-marker-overlay button[title="browser-marker"]').click();
  assert.equal(await page.getByRole("textbox", { name: "Marker name" }).inputValue(), "browser-marker");
  assert.equal(await page.locator('.map-marker-overlay button[title="browser-marker"] svg.lucide-map-pin').count(), 1);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Add marker", exact: true }).click();
  await page.getByText("Click the map where you want the marker.", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Cancel placement" }).click();
  const sharePage = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await sharePage.route("https://campus-share.test/**", async (route) => {
    const requestUrl = new URL(route.request().url());
    const response = await route.fetch({ url: `${base}${requestUrl.pathname}${requestUrl.search}` });
    await route.fulfill({ response });
  });
  await sharePage.route("https://maps.googleapis.com/**", (route) => route.abort());
  await sharePage.addInitScript(() => {
    Object.defineProperty(navigator, "share", { value: async (data) => { window.sharedPlace = data; }, configurable: true });
  });
  await sharePage.goto(`https://campus-share.test/?place=${published.images.at(-1).locationId}`);
  await sharePage.getByRole("heading", { name: "browser-marker", exact: true }).waitFor();
  await sharePage.getByRole("button", { name: "Share", exact: true }).click();
  const shared = await sharePage.evaluate(() => window.sharedPlace);
  assert.equal(shared.url, `https://campus-share.test/?place=${published.images.at(-1).locationId}`, "Share uses the public domain and selected place");
  await sharePage.goto(shared.url);
  await sharePage.getByRole("heading", { name: "browser-marker", exact: true }).waitFor();
  await sharePage.close();
  assert.deepEqual(errors, [], "No uncaught browser errors");
  console.log("PASS: PNG upload, pin marker and destination photo, private draft, drag, keyboard selection, publish, public click, reload persistence and mobile placement.");
} catch (error) {
  if (page) {
    await mkdir("test-results", { recursive: true });
    await page.screenshot({ path: "test-results/map-image-editor-failure.png", fullPage: true });
    console.error((await page.locator("body").innerText()).slice(0, 1400));
  }
  throw error;
} finally {
  await browser?.close();
  if (server.exitCode === null) { const exited = new Promise((resolve) => server.once("exit", resolve)); server.kill(); await exited; }
  if (path.dirname(directory) === path.resolve(tmpdir()) && path.basename(directory).startsWith("sns-map-browser-test-")) await rm(directory, { recursive: true, force: true });
}
